version: '3'
services:
  app:
    image: alekseyvy/docker_app:1.4
    restart: always
    ports:
    - ${PORT}:${DOCKER_PORT}
    volumes:
      - logs:/src/logs
    depends_on:
      - db
  db:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/src/db_data

networks:
  node_net:
    driver: bridge

volumes:
  logs:
  db-data: